# Generated by Django 3.1.6 on 2021-02-18 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('clave', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valores', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now=True)),
                ('observaciones', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('examenes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.examenes')),
            ],
        ),
    ]
