# Generated by Django 3.1.6 on 2021-02-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examenes',
            old_name='valores',
            new_name='valor',
        ),
    ]
