# Generated by Django 3.1.6 on 2021-02-18 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='email',
            new_name='correo',
        ),
    ]
