# Generated by Django 3.1.6 on 2021-02-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenes',
            name='fecha',
            field=models.DateField(),
        ),
    ]
