# Generated by Django 3.1.6 on 2021-02-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210218_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='clave',
            field=models.CharField(default='123456', max_length=50),
        ),
    ]
