# Generated by Django 3.1.6 on 2021-02-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210220_0300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examenes',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
