# Generated by Django 3.1.6 on 2021-02-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210218_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='apellido',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='educacion',
            field=models.TextField(default='complete la info'),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='foto',
            field=models.CharField(default='complete info', max_length=100),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='historial',
            field=models.TextField(default='complete la info'),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='ocupacion',
            field=models.CharField(default='influencer', max_length=150),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='resumen',
            field=models.TextField(default='complete la info'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='correo',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
