# Generated by Django 3.1.7 on 2021-03-06 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('observaciones', models.CharField(max_length=250)),
                ('summary', models.TextField(help_text='Enter a brief description of the examen', max_length=1000)),
                ('rut', models.CharField(help_text='9 Character', max_length=9, unique=True, verbose_name='RUT')),
            ],
            options={
                'ordering': ['nombre', 'paciente'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a examen genre (e.g. Science Fiction, French Poetry etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the examen's natural language (e.g. English, French, Japanese etc.)", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foto_perfil', models.CharField(default='complete info', max_length=65535)),
                ('Rut', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Nacimiento', models.DateField(blank=True, null=True)),
                ('Edad', models.IntegerField()),
                ('Telefono', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=150)),
                ('Correo', models.EmailField(max_length=200)),
                ('Password', models.CharField(default='123456', max_length=50)),
                ('Ocupacion', models.CharField(default='influencer', max_length=150)),
                ('Resumen', models.TextField(default='complete la info')),
                ('Educacion', models.TextField(default='complete la info')),
                ('Historial', models.TextField(default='complete la info')),
                ('Rol', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['Nombre'],
            },
        ),
        migrations.CreateModel(
            name='examenInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular examen across whole library', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('d', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='d', help_text='examen availability', max_length=1)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('examen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.examen')),
            ],
            options={
                'ordering': ['due_back'],
                'permissions': (('can_mark_returned', 'Set examen as returned'),),
            },
        ),
        migrations.AddField(
            model_name='examen',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this examen', to='catalog.Genre'),
        ),
        migrations.AddField(
            model_name='examen',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.language'),
        ),
        migrations.AddField(
            model_name='examen',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.paciente'),
        ),
    ]
