# Generated by Django 3.1.7 on 2021-03-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={'ordering': ['Paciente', 'Nombre']},
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='fecha',
            new_name='Fecha',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='summary',
            new_name='Observaciones',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='paciente',
            new_name='Paciente',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='rut',
            new_name='Rut',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='valor',
            new_name='Valor_Examen',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='language',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='observaciones',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Educacion',
            field=models.TextField(default='Ingrese estudios'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Foto_perfil',
            field=models.CharField(default='Inserte una URL', max_length=65535),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Historial',
            field=models.TextField(default='Ingrese historial clinico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Nacimiento',
            field=models.DateField(blank=True, default='05/12/2020', null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Resumen',
            field=models.TextField(default='Ingrese un breve resumen'),
        ),
    ]
