# Generated by Django 3.1.7 on 2021-03-06 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210306_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='Rut',
        ),
    ]
