# Generated by Django 3.1.7 on 2021-03-06 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_examen_rut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={'ordering': ['paciente', 'Nombre']},
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='Paciente',
            new_name='paciente',
        ),
    ]
