# Generated by Django 3.1.7 on 2021-03-07 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210306_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exameninstance',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='exameninstance',
            name='examen',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AlterModelOptions(
            name='examen',
            options={'ordering': ['paciente', 'Nombre'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
        migrations.AlterField(
            model_name='examen',
            name='Observaciones',
            field=models.TextField(help_text='Ingrese una breve descripcion del examen.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='examen',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.paciente'),
        ),
        migrations.DeleteModel(
            name='examenInstance',
        ),
    ]
