# Generated by Django 3.1.7 on 2021-03-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210307_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={'ordering': ['paciente', 'Nombre'], 'permissions': (('caaaaaaaaaaaan_mark_returned', 'Seeeeeeeeeeeet book as returned'),)},
        ),
    ]
