# Generated by Django 3.1.7 on 2021-03-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210307_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={'ordering': ['paciente', 'Nombre'], 'permissions': (('NO_PUEDE_BORRAR_EXAMEN', 'BORRAR DENEGADO'),)},
        ),
    ]
