# Generated by Django 3.1.7 on 2021-03-07 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210307_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={'ordering': ['paciente', 'Nombre'], 'permissions': (('PUEDES_BORRAR_EXAMEN', 'BORRAR CONCEDIDO'),)},
        ),
    ]
