# Generated by Django 3.1.7 on 2021-03-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210307_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={'ordering': ['paciente', 'Nombre'], 'permissions': (('acceso_natural', 'Control de edicion y eliminacion'),)},
        ),
    ]
