# Generated by Django 3.1.7 on 2021-03-07 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210307_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['Nombre'], 'permissions': (('acceso_natural', 'Control de edicion y eliminacion'),)},
        ),
    ]
