# Generated by Django 3.1.6 on 2021-02-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='foto',
            field=models.CharField(default='complete info', max_length=65535),
        ),
    ]
